In [ ]:
pip install pandas

In [ ]:
pip install numpy

In [ ]:
import pandas as pd
import numpy as np

df_employees = pd.read_csv("/content/employees_large.csv")
avg_salary_per_dept = df_employees.groupby("Department")["Salary"].mean()
highest_salary_dept = avg_salary_per_dept.idxmax()
print("Average Salary Per Department:\n", avg_salary_per_dept)
print("Department with Highest Average Salary:", highest_salary_dept)

Average Salary Per Department:
 Department
Engineering    125000.0
Finance         78000.0
HR              68000.0
IT              57750.0
Marketing       43750.0
Name: Salary, dtype: float64
Department with Highest Average Salary: Engineering


In [ ]:
df_sales = pd.read_csv("/content/sales_large.csv")
total_sales = df_sales.groupby(["Region", "Product"])["Sales"].sum()
highest_selling_product = total_sales.idxmax()
print("Total Sales Per Product Per Region:\n", total_sales)
print("Product with Highest Total Sales:", highest_selling_product)

Total Sales Per Product Per Region:
 Region   Product
Central  Apples      9000
         Oranges     8000
East     Apples      5000
         Bananas     8500
         Oranges    13900
North    Apples      7200
         Bananas     9000
         Oranges     4900
South    Apples     12900
         Bananas     5100
         Oranges     3000
West     Apples     18900
         Bananas    14700
         Oranges     7500
Name: Sales, dtype: int64
Product with Highest Total Sales: ('West', 'Apples')


In [ ]:
A = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B = np.array([[8, 5, 2], [7, 4, 1], [6, 3, 0]])
print("Element-wise Sum:\n", A + B)
print("Element-wise Product:\n", A * B)
print("Dot Product of A and B Transpose:\n", np.dot(A, B.T))
print("Determinant of A:", np.linalg.det(A))

Element-wise Sum:
 [[10  9  8]
 [ 8  7  6]
 [13 12 11]]
Element-wise Product:
 [[16 20 12]
 [ 7 12  5]
 [42 27  0]]
Dot Product of A and B Transpose:
 [[ 48  36  24]
 [ 33  24  15]
 [123  96  69]]
Determinant of A: 0.0


In [ ]:
random_data = np.random.randn(10000)
print("Mean:", np.mean(random_data))
print("Median:", np.median(random_data))
print("Standard Deviation:", np.std(random_data))
print("Min Value:", np.min(random_data))
print("Max Value:", np.max(random_data))
print("Count Mean:", np.sum(random_data > np.mean(random_data)))
norm_data = (random_data - np.min(random_data)) / (np.max(random_data) - np.min(random_data))
print("Normalized Data:\n", norm_data[:10])

Mean: -0.011226777683112551
Median: -0.01013526865673535
Standard Deviation: 0.9833551261461936
Min Value: -4.143040764716226
Max Value: 3.441361106285078
Count Greater than Mean: 5004
Normalized Data Sample:
 [0.54625346 0.59830764 0.40973867 0.67002479 0.52855771 0.46201318
 0.55738207 0.71016843 0.64311586 0.40648767]


In [ ]:
temperatures = [28, 32, 35, 31, 29, 30, 33, 36, 27, 25, 34, 30, 29, 37, 38, 26, 31, 35, 33, 32, 36, 34, 29, 28, 27, 35, 32, 30, 31, 33]
high_temp = [t for t in temperatures if t > 32]
temp_classification = [(t, "Hot" if t > 35 else "Warm" if t >= 30 else "Cool") for t in temperatures]
monthly_avg = sum(temperatures) / len(temperatures)
temp_diff = [t - monthly_avg for t in temperatures]
print("Temperatures Above 32C:\n", high_temp)
print("Temperature:\n", temp_classification)
print("Temperature Differences from Average:\n", temp_diff)

Temperatures Above 32C:
 [35, 33, 36, 34, 37, 38, 35, 33, 36, 34, 35, 33]
Temperature Classification:
 [(28, 'Cool'), (32, 'Warm'), (35, 'Warm'), (31, 'Warm'), (29, 'Cool'), (30, 'Warm'), (33, 'Warm'), (36, 'Hot'), (27, 'Cool'), (25, 'Cool'), (34, 'Warm'), (30, 'Warm'), (29, 'Cool'), (37, 'Hot'), (38, 'Hot'), (26, 'Cool'), (31, 'Warm'), (35, 'Warm'), (33, 'Warm'), (32, 'Warm'), (36, 'Hot'), (34, 'Warm'), (29, 'Cool'), (28, 'Cool'), (27, 'Cool'), (35, 'Warm'), (32, 'Warm'), (30, 'Warm'), (31, 'Warm'), (33, 'Warm')]
Temperature Differences from Average:
 [-3.533333333333335, 0.466666666666665, 3.466666666666665, -0.533333333333335, -2.533333333333335, -1.533333333333335, 1.466666666666665, 4.466666666666665, -4.533333333333335, -6.533333333333335, 2.466666666666665, -1.533333333333335, -2.533333333333335, 5.466666666666665, 6.466666666666665, -5.533333333333335, -0.533333333333335, 3.466666666666665, 1.466666666666665, 0.466666666666665, 4.466666666666665, 2.466666666666665, -2.533333333